# Refresh source-owned gameplay files without touching extracted Warcraft data.
if(NOT DEFINED WAR1GUS_SOURCE_DIR OR NOT IS_ABSOLUTE "${WAR1GUS_SOURCE_DIR}" OR
   NOT IS_DIRECTORY "${WAR1GUS_SOURCE_DIR}")
  message(FATAL_ERROR "WAR1GUS_SOURCE_DIR must be an existing absolute source directory")
endif()
if(NOT DEFINED WAR1GUS_DATA_DIR OR NOT IS_ABSOLUTE "${WAR1GUS_DATA_DIR}" OR
   NOT IS_DIRECTORY "${WAR1GUS_DATA_DIR}")
  message(FATAL_ERROR "WAR1GUS_DATA_DIR must be an existing absolute extracted data directory")
endif()
if(NOT EXISTS "${WAR1GUS_DATA_DIR}/war1data" OR
   IS_DIRECTORY "${WAR1GUS_DATA_DIR}/war1data")
  message(FATAL_ERROR "WAR1GUS_DATA_DIR has no war1data extraction marker: ${WAR1GUS_DATA_DIR}")
endif()

get_filename_component(source_dir "${WAR1GUS_SOURCE_DIR}" REALPATH)
get_filename_component(data_dir "${WAR1GUS_DATA_DIR}" REALPATH)
if(source_dir STREQUAL data_dir)
  message(FATAL_ERROR "Source and extracted data directories must differ")
endif()
string(FIND "${data_dir}/" "${source_dir}/" data_in_source)
if(data_in_source EQUAL 0)
  message(FATAL_ERROR "Extracted data must not be inside the source directory")
endif()
foreach(asset_dir scripts campaigns maps)
  if(NOT IS_DIRECTORY "${source_dir}/${asset_dir}")
    message(FATAL_ERROR "Missing source asset directory: ${source_dir}/${asset_dir}")
  endif()
endforeach()

# Visit only asset directories and prune generated/package trees before descending.
function(sync_asset_tree relative_dir)
  file(GLOB entries LIST_DIRECTORIES true "${source_dir}/${relative_dir}/*")
  foreach(entry IN LISTS entries)
    if(IS_SYMLINK "${entry}")
      continue()
    endif()
    get_filename_component(name "${entry}" NAME)
    if(name MATCHES "^(\\.git|build|cmake-build[^/]*|generated|ai-training|ai-evaluation|checkpoints?)$")
      continue()
    endif()
    file(RELATIVE_PATH relative "${source_dir}" "${entry}")
    if(relative STREQUAL "scripts/ai/war1gus")
      continue()
    endif()
    if(IS_DIRECTORY "${entry}")
      sync_asset_tree("${relative}")
    elseif((relative_dir MATCHES "^(scripts|campaigns)(/|$)" AND name MATCHES "\\.lua$") OR
           (relative_dir MATCHES "^maps(/|$)" AND name MATCHES "\\.(smp|sms|png)$"))
      if(name STREQUAL "wc1-config.lua")
        continue()
      endif()
      get_filename_component(relative_parent "${relative}" DIRECTORY)
      string(REPLACE "/" ";" components "${relative_parent}")
      set(destination_parent "${data_dir}")
      foreach(component IN LISTS components)
        if(IS_SYMLINK "${destination_parent}/${component}")
          message(FATAL_ERROR "Refusing symlinked extracted data directory: ${relative}")
        endif()
        set(destination_parent "${destination_parent}/${component}")
        file(MAKE_DIRECTORY "${destination_parent}")
      endforeach()
      if(IS_SYMLINK "${data_dir}/${relative}")
        message(FATAL_ERROR "Refusing symlinked extracted data file: ${relative}")
      endif()
      file(COPY "${entry}" DESTINATION "${destination_parent}")
    endif()
  endforeach()
endfunction()

foreach(asset_dir scripts campaigns maps)
  sync_asset_tree("${asset_dir}")
endforeach()
message(STATUS "Refreshed source Lua and maps in ${data_dir}")
